set_property SRC_FILE_INFO {cfile:{C:/Users/aaron/Desktop/College Work/3rd Year/3C7/Lab D/modulator/modulator.srcs/constrs_1/new/modulator.xdc} rfile:../../../modulator.srcs/constrs_1/new/modulator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports pwm_out]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports sw0]
